apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kong-operator
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings", "clusterroles"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

# - apiGroups: ["admissionregistration.k8s.io"]
#   resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
#   verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
