apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: kong-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]

- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]

- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]

- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]

- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]  

- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
  
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]

- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["apps"]
  resourceNames: ["kong-operator"]
  resources: ["deployments/finalizers"]
  verbs: ["update"]

- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["helm.operator-sdk"]
  resources: ["kongs", "kongs/status"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]